services:
  auth-service:
    build: ./auth-service
    entrypoint: ["doppler", "run", "--", "node", "dist/index.js"]
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    volumes:
      - ./auth-service/data:/app/data
    networks:
      - local_net
    ports:
      - "3001:3001"

networks:
  local_net:
    driver: bridge